Portafolio_Web_2023/Models/CVsViewModel.cs
namespace Portafolio_Web_2023.Models
{
    //Esta clase contendra el modelo de mi cv
    public class CVsViewModel
    {
        //Propiedades de mis cvs
        public int Id { get; set; } 
        public string Nombre { get; set; }
        //public string Ruta { get; set; }
    }
}

Portafolio_Web_2023/Models/CVs_VM_Resources/CVs_Portafolio_ViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Portafolio_Web_2023.Models.CVs_VM_Resources
{
    public class CVs_Portafolio_ViewModel
    {
        //Esta propiedad contendra el valor del elemento seleccionado
        public string CV_Seleccionado { get; set; }

        //Propiedad de visualización
        //contendra el id y el nombre y posiblemente ruta
        public List<SelectListItem> cvs_selectListItems { get; set; }
    }
}

Portafolio_Web_2023/Models/ContactoViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Portafolio_Web_2023.Models
{
    public class ContactoViewModel
    {

        [Required(ErrorMessage = "* El campo {0} es obligatorio.")]
        [StringLength(150, MinimumLength = 3, ErrorMessage = "El campo {0} debe tener una longitud miníma de {2} y máxima de {1} caracteres.")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "* El campo {0} es obligatorio.")]

        [EmailAddress(ErrorMessage = "Ingrese una dirección de correo válida.")]
        [DisplayName("Correo")]
        public string Email { get; set; }

        [Compare("Email", ErrorMessage = "Ambos correos no coinciden.")]
        [DisplayName("Confirmar correo")]
        public string ConfirmarEmail { get; set; }

        [Required(ErrorMessage = "* El campo {0} es obligatorio.")]
        [DataType(DataType.MultilineText)]
        public string Mensaje { get; set; }
    }
}

Portafolio_Web_2023/Models/ErrorViewModel.cs
namespace Portafolio_Web_2023.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Portafolio_Web_2023/Models/PortafolioIndexViewModel.cs
namespace Portafolio_Web_2023.Models
{
	public class PortafolioIndexViewModel
    {
		public IEnumerable<ProyectoViewModel> Proyectos { get; set; }
	}
}

Portafolio_Web_2023/Models/ProyectoViewModel.cs
namespace Portafolio_Web_2023.Models
{
	public class ProyectoViewModel
	{
		public string Titulo { get; set; }
		public string Descripcion { get; set; }
		public string ImagenURL { get; set; }
		public string Link { get; set; }
	}
}

Portafolio_Web_2023/Controllers/PortafolioWController.cs
using Microsoft.AspNetCore.Mvc;
using Portafolio_Web_2023.Models;
using Portafolio_Web_2023.Services;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc.Rendering;
using Portafolio_Web_2023.Models.CVs_VM_Resources;

namespace Portafolio_Web_2023.Controllers
{
    public class PortafolioWController : Controller
    {
        #region Campos generados automáticamente
        private readonly ILogger<PortafolioWController> logger;
        private readonly IRepositorioProyecto repositorioProyecto;
        private readonly IServicioEmailSendGrid servicioEmailSendGrid;
        //private readonly IRepositorioArchivos repositorioArchivos;
        #endregion

        public PortafolioWController(ILogger<PortafolioWController> logger, IRepositorioProyecto repositorioProyecto, IServicioEmailSendGrid servicioEmailSendGrid/*, IRepositorioArchivos repositorioArchivos*/)
        {
            //Generados automáticamente
            this.logger = logger;
            this.repositorioProyecto = repositorioProyecto;
            this.servicioEmailSendGrid = servicioEmailSendGrid;
            //this.repositorioArchivos = repositorioArchivos;
        }

        public IActionResult Index()
        {            
            var proyectos = repositorioProyecto.ObtenerListadoProyectos().Take(3).ToList();

            var modelo = new PortafolioIndexViewModel
            {
                Proyectos = proyectos
            };
           
            return View(modelo);
        }

        public IActionResult Proyectos()
        {
            //Pasamos todos los proyectos
            var proyectos = repositorioProyecto.ObtenerListadoProyectos();

            return View(proyectos);
        }

        [HttpGet]
        public IActionResult Cv()
        {                       
            var cvsData = new RepositorioArchivos().ListadoArchivos();

            //Inicializamos el modelo que contendra la lista y el elemento seleccionado 
            //para asi pasar los datos del repo al modelo list
            var modelo = new CVs_Portafolio_ViewModel();
            modelo.cvs_selectListItems = new List<SelectListItem>();

            //Ahora un bucle que ira recorriendo y mostrando las propiedades
            foreach (var cvs in cvsData)
            {
                modelo.cvs_selectListItems.Add(new SelectListItem { Text = cvs.Nombre, Value = cvs.Id.ToString() });
            }

            return View("cv", modelo);
        }

        [HttpPost]
        public IActionResult Cv(CVs_Portafolio_ViewModel cVs_Portafolio_ViewModel)
        {

            //switch expresión
            return cVs_Portafolio_ViewModel.CV_Seleccionado.ToString() switch
            {
                "1" => RedirectToAction("ArchivoHtml"),
                "2" => RedirectToAction("ArchivoCanvaConFoto"),
                _ => RedirectToAction("cv"),
            };

            ////Anterior
            //switch (cVs_Portafolio_ViewModel.CV_Seleccionado.ToString())
            //{
            //    case "1":
            //        return RedirectToAction("ArchivoHtml");

            //    case "2":
            //        return RedirectToAction("ArchivoCanvaConFoto");

            //    default:
            //        return RedirectToAction("cv");
            //        //    break;
            //}

            //if (cVs_Portafolio_ViewModel.CV_Seleccionado == "1")
            //{
            //    return RedirectToAction("ArchivoHtml");
            //}
            //else if (cVs_Portafolio_ViewModel.CV_Seleccionado == "2")
            //{
            //    return RedirectToAction("ArchivoCanvaConFoto");
            //}
            //else if (obInt == 3)
            //{
            //    return RedirectToAction("ArchivoCanvaSinFoto");
            //
            //}
            //return View("cv",cVs_Portafolio_ViewModel);
            //return RedirectToAction("cv");
        }

        ////V#9 Decarga de archivo von FileResult
        ////RETORNAR UN ARCHIVO DE NUESTRO SERVIDOR AL USUARIO(Descargar)
        public FileResult ArchivoHtml()
        {           
            var ruta = "/Resources/Simple Cv-Carlos-Herrera.pdf";
            //var ruta = repositorioArchivos.ListadoArchivos();
            //ruta = Server.MapPath("./Resources/Intro Exel.pdf");
            return File(ruta, "application/pdf", "Cv-Simple-Carlos-Herrera.pdf");
        }

        public FileResult ArchivoCanvaConFoto()
        {           
            var ruta = "/Resources/Cv-Carlos-Herrera Canva.pdf";

            return File(ruta, "application/pdf", "Cv-Carlos-Herrera Canva.pdf");
        }

        [HttpGet]
        public IActionResult Contacto()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Contacto(ContactoViewModel contactoViewModel)
        {          
            try
            {               
                if (ModelState.IsValid)
                {
                    await servicioEmailSendGrid.Enviar(contactoViewModel);
                    return RedirectToAction("Gracias");
                }
            }
            catch (Exception ex)
            {
                //Console.WriteLine($"Error de envio, los detalles son los siguientes:\n{ex.Message}");
                
                string message = $"Error de envio, los detalles son los siguientes:{ex.Message}";
                logger.LogError(message);

                //Thread.Sleep(500);
                ViewBag.msjError = "¡No se ha podido enviar el formulario, por favor intente por otro medio!";
            }
            return View(contactoViewModel);
        }

        [HttpGet]
        public IActionResult Gracias()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Portafolio_Web_2023/Views/PortafolioW/Contacto.cshtml
@model Portafolio_Web_2023.Models.ContactoViewModel

@{
    ViewData["Title"] = "Contacto - ";
    // Layout = null;

    Layout = "~/Views/Shared/_Layout_Contacto.cshtml";
}


@* Si el contenido del msj es distinto a null se mostrara la alerta
Ya que si es null es porque se envio o enviara correctamente el formulario *@
@if (ViewBag.msjError != null)
{
    <div class="alert alert-danger d-flex alert-dismissible fade show text" role="alert">
        <div>
            @ViewBag.msjError
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
}

<div class="text-center">
    @* Imagen obtenida de: https://undraw.co/illustrations *@
    <img class="img-fluid img-center mb-sm-3 mb-md-2 mb-lg-4 chat-grup" src="~/img/undraw_group_chat.svg" alt="undraw_group_chat.svg" title="chat grupal.svg"/>

    <div class="text-uppercase mb-sm-2 mb-md-3 mb-lg-4 text">
        <h1 class="mb-0 card-title">Envíeme un correo</h1>
        <p class="mt-0" style="color: #9DA3A8">Proporcionado por la Web API de SendGrid</p>
    </div>
    <div class="row justify-content-center mt-sm-2 mt-md-4 mt-lg-5">
        <div class=" col-sm-6 col-md-9 col-lg-12">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <form asp-action="Contacto" class="fw-bolder" method="post">
                <div class="form-group mb-sm-2 mb-md-3 mb-lg-4 text">
                    <label asp-for="Nombre" class="control-label fw-bold mb-sm-1 mb-md-2 mb-lg-3"></label>
                    <input asp-for="Nombre" class="form-control fw-normal mb-2 mb-sm-2 mb-md-2 mb-lg-2 text" placeholder="Ingrese su nombre." />
                    <span asp-validation-for="Nombre" class="text-danger fw-light mb-1 mb-sm-2 mb-md-2 mb-lg-2"></span>
                </div>
                <div class="form-group mb-sm-2 mb-md-3 mb-lg-4 text">
                    <label asp-for="Email" class="control-label fw-bold mb-sm-1 mb-md-2 mb-lg-3"></label>
                    <input asp-for="Email" class="form-control fw-normal mb-2 mb-sm-2 mb-md-2 mb-lg-2 text" placeholder="correo@gmail.com" />
                    <span asp-validation-for="Email" class="text-danger fw-light mb-1 mb-sm-2 mb-md-2 mb-lg-2"></span>
                </div>
                <div class="form-group mb-sm-2 mb-md-3 mb-lg-4 text">
                    <label asp-for="ConfirmarEmail" class="control-label fw-bold mb-sm-1 mb-md-2 mb-lg-3"></label>
                    <input asp-for="ConfirmarEmail" class="form-control fw-normal mb-2 mb-sm-2 mb-md-2 mb-lg-2 text" placeholder="correo@gmail.com" />
                    <span asp-validation-for="ConfirmarEmail" class="text-danger fw-light mb-1 mb-sm-2 mb-md-2 mb-lg-2"></span>
                </div>
                <div class="form-group mb-sm-2 mb-md-3 mb-lg-4 text">
                    <label asp-for="Mensaje" class="control-label fw-bold mb-sm-1 mb-md-2 mb-lg-3"></label>
                    <textarea asp-for="Mensaje" class="form-control fw-normal mb-2 mb-sm-2 mb-md-2 mb-lg-2 text" placeholder="Escriba su mensaje."></textarea>
                    <span asp-validation-for="Mensaje" class="text-danger fw-light mb-1 mb-sm-2 mb-md-2 mb-lg-2"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Enviar" class="btn btn-primary text mb-3" />               
                </div>
            </form>
        </div>
    </div>
</div>


@* Lo que debía escribir *@
@section Scripts {
    @{
        // await Html.RenderPartialAsync("_ValidationScriptsPartial");
            <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

Portafolio_Web_2023/Views/PortafolioW/Gracias.cshtml
@{
    ViewData["Title"] = "Gracias - ";
    // Layout = null;
    Layout = "~/Views/Shared/_Layout_Contacto.cshtml";
}
            @* pantallas muy pequeñas (mt-0) *@
<div class="text-center  mt-3 mt-sm-5 mt-md-5 mt-lg-5 mt-xl-5 mt-xxl-5">
                @* Imagen obtenida de: https://undraw.co/illustrations *@
                <img class="img-fluid bg-white img-gracias" src="~/img/undraw_message.svg" alt="undraw_message.svg" title="Gracias.svg"/>

                @* pantallas muy pequeñas (mt-4) *@
                <div class="text-body text-wrap fs-2 mt-4 mt-sm-5 mt-md-5 mt-lg-5 mt-xl-5 mt-xxl-5">
                    <p class="fw-normal">Gracias por ponerse en contacto conmigo.</p>
                    <p class="texto-parpadear fw-bolder">¡Responderé lo más pronto posible!</p>
                    <p style="cursor: pointer" title="Happy">😃</p>
                </div>
            </div>

Portafolio_Web_2023/Views/PortafolioW/Index.cshtml
@model PortafolioIndexViewModel
@{
    ViewData["Title"] = "Inicio";
}

            <!--INICIO SECCIONES-->
            <div class="secciones">

                <!--INICIO SECCIÓN PROYECTOS RECIENTES-->
                <div class="seccion" id="Proyectos_recientes">
                    <partial name="PartialViews\_ProyectosRecientes_PV.cshtml" model="Model.Proyectos" />
                </div>
                <!--FIN SECCIÓN PROYECTOS RECIENTES-->

                <!--INICIO SECCIÓN TECNOLOGÍAS / HABILIDADES-->
                <div class="seccion" id="Habilidades">
                    <partial name="PartialViews\_Habilidades_PV.cshtml" />
                </div>
                <!--FIN SECCIÓN TECNOLOGÍAS / HABILIDADES-->

                <!--INICIO SECCIÓN PERFIL-->
                <div class="seccion" id="Perfil">
                    <partial name="PartialViews\_Perfil_PV.cshtml" />
                </div>
                <!--FIN SECCIÓN PERFIL-->

            </div>
            <!--FIN SECCIONES-->

Portafolio_Web_2023/Views/PortafolioW/PartialViews/_DropDownArchivos_PV.cshtml
@model Portafolio_Web_2023.Models.CVs_VM_Resources.CVs_Portafolio_ViewModel

<div id="ventanaModal" class="modal">
    <div class="ventana">
        @* Se le aplica el mismo diseño que al btn cerrar de la alerta *@
        <a class="closebtn" id="btn-cerrar" href="#" title="Cerrar ventana" style='text-decoration:none;'>
            &times;
        </a>

        <p class="titulo-modal">Archivos disponibles:</p>

        <form asp-controller="PortafolioW" asp-action="cv" method="post">      
            <div class="dropdown">
                @* LISTA CV DESDE EL SERVIDOR *@
                <select class="form-select" asp-items="Model.cvs_selectListItems" asp-for="CV_Seleccionado">
                    <option>Elija el archivo que desea descargar:</option>
                </select>

            </div>
            <div class="botones">
                @* PARA VOLVER LUEGO DE HACER CLICK *@
                @* <button class="btn-aceptar" onclick="history.back()">Aceptar</button> *@
                <button class="btn-aceptar">Aceptar</button>
                <a class="btn-cancelar" href="#">Cancelar</a>
            </div>
        </form>
    </div>
</div>

@* } *@

Portafolio_Web_2023/Views/PortafolioW/PartialViews/_Perfil_PV.cshtml
                    <!--SOBRE MÍ-->
                    <div class="card h-100">
                        <div class="contenido-card-perfil">

                            <div class="img-perfil">
                                <!--Imagen del sitio https://undraw.co/illustrations-->
                                <img class="img-p" src="~/img/undraw_profile.svg" alt="imagen-perfil.svg" title="imagen-perfil.svg">
                            </div>
                                <div class="texto-secciones">
                                    <h1>Sobre mí:</h1>                                
                                    <div class="overflow-scroll_p">
                                        @* <h4>Soy un desarrollador junior .Net con gran entusiasmo y ganas de aprender</h4> *@
                                        @* <p>Desarrollador de Software con experiencia en el desarrollo de proyectos personales utilizando el lenguaje de programación C#. Apasionado por la tecnología y enfocado en la creación de soluciones innovadoras, poseo un sólido conocimiento de los fundamentos de la programación y una capacidad demostrada para diseñar y desarrollar aplicaciones eficientes con C#.</p> *@
                                        <p>Mi nombre es <strong>Carlos Herrera</strong>, tengo <strong>23 años</strong> y cuento con pénsum cerrado en <strong>Ingeniería en Sistemas</strong>, poseo más de 2 años de experiencia en labores de programación, análisis y desarrollo de sistemas.</p>
                                        <br />
                                        <p>He tenido la oportunidad de trabajar en distintos proyectos que me han permitido poner a prueba mis habilidades tanto en backend como frontend, aunque mi área favorita es el backend haciendo uso de c# como lenguaje principal. Mi enfoque se centra en la resolución de problemas, construcción de software eficiente de alta calidad y en la mejora continua de mis habilidades técnicas. </p>
                                        <br />
                                        <p>Valoro la colaboración y el trabajo en equipo, y estoy comprometido a contribuir al éxito de los proyectos en los que participo. Mi objetivo a corto plazo es seguir aprendiendo y creciendo como desarrollador, adquiriendo experiencia en nuevas tecnologías y metodologías de desarrollo.</p>                                       
                                    </div>
                                </div>

                            <div class="card-footer-primary">
                                <ul class="menu">
                                    <li>
                                        <!--BOTÓN VER CV-->
                                        <a class="btn-secciones btn-pdd-perfil" asp-area="" asp-controller="PortafolioW" asp-action="cv">
                                            Ver CV
                                            <span class="border border-top"></span>
                                            <span class="border border-right"></span>
                                            <span class="border border-bottom"></span>
                                            <span class="border border-left"></span>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>

Portafolio_Web_2023/Views/PortafolioW/PartialViews/_ProyectosRecientes_PV.cshtml
@*   <!--//V#55 Pasando datos a una vista parcial--> *@
@model IEnumerable<ProyectoViewModel>
@if (Model is not null)
{


<!--MIS ÚLTIMOS PROYECTOS-->
                    <div class="card h-100">                        
                        <div class="contenido-card-recientes">
                            <div class="texto-secciones">
                                <h1>Mis trabajos recientes</h1>
                                <p>Aquí se muestrán algunos de mís trabajos más recientes.</p>
                            </div>

                            <div class="overflow-scroll_r">                        
                                <partial name="PartialViews\_TodosMisProyectos_PV" model="Model" />
                            </div>
                                    
                            <div class="card-footer-primary">
                                <ul class="menu">
                                    <li>
                                        <!--BOTÓN VER TODOS LOS PROYECTOS-->
                                        <a class="btn-secciones btn-pdd-recientes" asp-area="" asp-controller="PortafolioW" asp-action="Proyectos">
                                            Ver todos los proyectos
                                            <span class="border border-top"></span>
                                            <span class="border border-right"></span>
                                            <span class="border border-bottom"></span>
                                            <span class="border border-left"></span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
}

Portafolio_Web_2023/Views/PortafolioW/Proyectos.cshtml
@{
    ViewData["Title"] = " Mis proyectos - ";
    Layout = "~/Views/Shared/_Layout_Proyectos.cshtml";
}

<div class="contenido-proyectos mb-3 mb-sm-4">
                    <h1 class="title text-uppercase">Todos mis proyectos</h1>
                    <p class="contenido">Aquí encontrarás todos los proyectos en los que he trabajado.</p>
                </div>

<partial name="PartialViews/_TodosMisProyectos_PV.cshtml" />

Portafolio_Web_2023/Views/Shared/_Layout_Contacto.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    @*  ¿Cómo podemos impedir que los navegadores móviles escalen nuestros sitios y los miniaturicen? La solución
    es una nueva etiqueta meta cuyo name es “viewport”, que solo es aplicada por dispositivos móviles y es
    ignorada en computadoras de escritorio. *@
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Portafolio Web 2023</title>
    @* Bootstrap *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    @* CSS *@
    <link rel="stylesheet" href="~/css/tarjeta_proyectos.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/css/mediaquerys.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/css/contacto.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/media-movil-small.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/media-movil-md.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/media-tablet.css" asp-append-version="true">

</head>
<body>
    <header>
        <nav class="navbar fixed-top bg-opacity-10">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="PortafolioW" asp-action="Index">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" class="bi bi-arrow-left d-inline-block align-text-top" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
                    </svg>
                    Regresar al Inicio
                </a>
            </div>
        </nav>
    </header>

    <div class="container pt-5">
        <main role="main" class="pt-5">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Portafolio_Web_2023/Views/Shared/_Layout_cv.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    @*  ¿Cómo podemos impedir que los navegadores móviles escalen nuestros sitios y los miniaturicen? La solución
    es una nueva etiqueta meta cuyo name es “viewport”, que solo es aplicada por dispositivos móviles y es
    ignorada en computadoras de escritorio. *@
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Portafolio Web 2023</title>

    <link rel="stylesheet" href="~/css/cv.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/botones-desing.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/css/mediaquerys.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/css/footer.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/media-movil-small.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/media-movil-md.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/media-tablet.css" asp-append-version="true">

</head>
<body>
    <header>
       
        @* Creando alerta *@
        <nav class="barra-nav top-nav">
            @* A este div va a apuntar mi funcion js para cerrar el elemento automáticamente *@
            <div class="alert-cv">
                @* Se usa un texto o simbolo html para crear la X que es: &times *@
                <span class="closebtn" onclick="this.parentElement.style.display='none';" title="Cerrar alerta">&times;</span>
                Se esta mostrando una vista HTML de mi cv, si desea puede descargarlo o en su lugar uno con diseño hecho en Canva, haciendo click en el botón <strong>Descargar CV</strong>.
            </div>
          
            <div class="cont-nav">

                <!--Botón para regresar en pantallas grandes-->
                @* Se utiliza un evento JS de OnClick para regresar a la página y estado anterior *@
                <a class="img-nav" asp-area="" asp-controller="PortafolioW" asp-action="Index">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" class="bi bi-arrow-left d-inline-block align-text-top" viewBox="0 0 16 16">
                        <title>Regresar</title>
                        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
                    </svg>
                </a>
                <a class="texto-nav" title="Regresar al Inicio" asp-area="" asp-controller="PortafolioW" asp-action="Index">Regresar al Inicio</a>

                <!--Botón para descargar en pantallas grandes-->
                <a class="boton-descargar" href="#ventanaModal">Descargar CV</a>
            </div>

            <!--Botón para regresar en pantallas pequeñas-->
            <div class="btn-regresar-min">                
                <a class="cont-regresar" asp-area="" asp-controller="PortafolioW" asp-action="Index">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" class="bi bi-arrow-left d-inline-block align-text-top" viewBox="0 0 16 16">
                        @* <title>Regresar al Inicio</title> *@
                        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" fill="#0d6efd" />
                    </svg>
                    Regresar
                </a>
            </div>

            <!--Botón para descargar en pantallas pequeñas-->
            <div class="btn-descargar-cv">
                <a class="btn-a" href="#ventanaModal">Descargar CV</a>
            </div>
        </nav>      

    </header>
    @*     <div class="superior"> *@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="/Views/PortafolioW/PartialViews/_DropDownArchivos_PV.cshtml" />
        </main>
    </div>
    @*  </div> *@

    <footer>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js" asp-append-version="true"></script>
    <script src="~/js/cv_contacto.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>